### ISSUE TITLE
FAQ page is not opening when language is by default english

### ISSUE THREAD

**Issue by arvat** [arvat/crmi#1]

**Comment by pooshkin** [comment]
messages.properties contains default configuration information. But each language need to be localizated - messages_ro.properties, _ru..., _uk..., _by..., _kz..., and so on... even english _en. So I added a simlink to messages.properties nad name it messages_en.properties. Now english language is loading properly.

**Comment by arvat** [comment]
Yesterday I tested the system. Bug still persist.

**Comment by pooshkin** [comment]
Fixed. We fix the bug by replacing string in /src/main/java/org/arvat/crmi/config/MvcConfig.java from:

19.        clr.setDefaultLocale(Locale.US);

to

19.        clr.setDefaultLocale(Locale.ENGLISH);
