### ISSUE TITLE
User hostile message when selecting "NULL" publisher  name in a "New Report"

### ISSUE THREAD

**Issue by dceban** [arvat/crmi#21]
**Steps to reproduce:**
1. Go to "New Report" page.
2. Enter an invalid publisher name in the respective field.
3. Complete the rest of the required fields.
4. Click "Apply". 

**Actual results:**
A user-hostile message appears. 

**Expected results:**
Display a user-friendly validation message. 

https://youtu.be/tixEoUvoBzQ

**Comment by arvat** [comment]
Fixed, thanks a lot.
