### ISSUE TITLE
Restrictions removed from some check-boxes after applying the changes. 

### ISSUE THREAD

**Issue by dceban** [arvat/crmi#25]
**Steps to reproduce:**
1. Go to a publisher's details page. 
2. Select the "Female" gender. 
3. Click "Apply".
4. Select the "Elder" or "Ministerial Servant" check-boxes.
5. Apply the changes.

**Actual results:**
When selecting the "Female" gender, the "Elder" and "Ministerial Servant" check-boxes are set to read-only. Once the user applies the changes one time, these check-boxes become available and are being saved for a Female publisher. 

**Expected results:**
"Elder" and "Ministerial Servant" check-boxes are expected to remain unavailable as long as the Female gender is selected. 

https://youtu.be/Kbt35woxkis

**Comment by arvat** [comment]
Fixed
