### ISSUE TITLE
Make some checkboxes unavailable for unbaptized publishers

### ISSUE THREAD

**Issue by dceban** [arvat/crmi#27]
**Steps to reproduce:**
1. Go to the "New Publisher" page.
2. Complete the required fields. 
3. Select the check-boxes: Elder, Regular Pioneer, Anointed. 
4. Make sure that the "Date Immersed" field is empty.
5. Save the changes. 

![image](https://user-images.githubusercontent.com/45683544/50563433-72a6dd00-0d25-11e9-9b95-23d1f0bdbb0d.png)

**Actual results:**
The publisher is an Elder, Regular Pioneer and Anointed, even though still not baptized. 

![image](https://user-images.githubusercontent.com/45683544/50563470-bdc0f000-0d25-11e9-9cf9-9c7927a24405.png)

**Expected results:**
If the user selects positions that require the publisher to be baptized, make the "Date Immersed" field mandatory. 
Another option would be to automatically remove the "Unbaptized publisher" tag from the publisher's "Personal information" if the user selects any check-box that requires the publisher to be baptized.

**Comment by arvat** [comment]
Thanks, fixed
