### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by arvat** [arvat/crmi#7]
Please translate to other languages
telegram.bot.text_missing_group_reports=Dear brother, please keep in mind that these reports are missing in your group: {LIST}

**Comment by pooshkin** [comment]
Done

**Comment by arvat** [comment]
Te rog si aceasta valoare din engleza
personalDataConsentUncheck=

În mar., 20 nov. 2018 la 11:26, Vladimir Arvat <vladart.14@gmail.com> a
scris:
